=== pwsafe/pwsafe/pwsafe/pwsafe/src/ui/Windows/Tools/VK Data Generator/user_keyboards.xsd
<?xml version="1.0" encoding="iso-8859-1" standalone="yes"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:annotation>
  <xs:documentation xml:lang="en">
    This XML Schema corresponds to V3.18 of Password Safe.
    This describes keyboards that cannot be extracted or need extra changes.
    Each keyboard must have a unique keyboard layout ID (KLID) and name.
    To make different from those in Winodws, these should end with 'FFF'.
    The Japanese keyboard is different as there are XX versions.
    
    Each keyboard has keys denoted by their scan code,  and then the 
    definition of the Unicode characters. Dead Keys and Multi-character
    values are not supported.
      b = base character (pressing the key without shift, caps, control or alt keys)
      l = with the Left Control key
      g = with the Alt Gr key
      r = with the Right Control key
    Then each of these can be with or without the Shift and Caps Lock key
      C = with the Caps Lock key
      s = with the Shift key (left or right)

    Giving four sets of four:
      "b, bC, sb, sbC", "l, lC, sl, slC", "g, gC, sg, sgC", "r, rC, sr, srC"
  </xs:documentation>
</xs:annotation>

<xs:simpleType name="klidType">
  <xs:restriction base="xs:hexBinary">
    <xs:length value="4" fixed="true" />
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="scType">
  <xs:restriction base="xs:hexBinary">
    <xs:length value="1" fixed="true" />
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="wcharType">
  <xs:restriction base="xs:hexBinary">
    <xs:length value="2" fixed="true" />
  </xs:restriction>
</xs:simpleType>

  <xs:element name="keyboards">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="keyboard" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="key" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="scancode" type="scType" use="required" />
                  <xs:attribute name="b"    type="wcharType" use="required" />
                  <xs:attribute name="bC"   type="wcharType" use="required" />
                  <xs:attribute name="sb"   type="wcharType" use="required" />
                  <xs:attribute name="sbC"  type="wcharType" use="required" />
                  <xs:attribute name="l"    type="wcharType" use="required" />
                  <xs:attribute name="lC"   type="wcharType" use="required" />
                  <xs:attribute name="sl"   type="wcharType" use="required" />
                  <xs:attribute name="slC"  type="wcharType" use="required" />
                  <xs:attribute name="g"    type="wcharType" use="required" />
                  <xs:attribute name="gC"   type="wcharType" use="required" />
                  <xs:attribute name="sg"   type="wcharType" use="required" />
                  <xs:attribute name="sgC"  type="wcharType" use="required" />
                  <xs:attribute name="r"    type="wcharType" use="required" />
                  <xs:attribute name="rC"   type="wcharType" use="required" />
                  <xs:attribute name="sr"   type="wcharType" use="required" />
                  <xs:attribute name="srC"  type="wcharType" use="required" />
                </xs:complexType>
                <xs:unique name="UniqueScancode">
                  <xs:selector xpath="key" />
                  <xs:field xpath="@scancode" />
                </xs:unique>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="klid" type="klidType" use="required" />
            <xs:attribute name="kname" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== pwsafe/pwsafe/src/ui/Windows/Tools/VK Data Generator/user_keyboards.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl"?>

<!--
    Special Notes:
    1. Korean keyboard:
          'b' == English
          'g' == Korean
    1. Japanese keyboard:
          'b' == English (only one width)
          'l' == Japanese Kana + Hiragana
          'g' == Japanese Kana + Katakana (full width)
          'r' == Japanese Kana + Katakana (half width)
-->

<keyboards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="user_keyboards.xsd">
  <keyboard klid="0001FFFF" kname="Chinese ChaJei">
    <key scancode="39" b="0020" bC="0020" sb="0020" sbC="0020" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="29" b="20ac" bC="20ac" sb="007e" sbC="007e" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="02" b="0031" bC="0031" sb="0021" sbC="0021" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="03" b="0032" bC="0032" sb="0040" sbC="0040" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="04" b="0033" bC="0033" sb="0023" sbC="0023" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="05" b="0034" bC="0034" sb="0024" sbC="0024" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="06" b="0035" bC="0035" sb="0025" sbC="0025" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="07" b="0036" bC="0036" sb="005e" sbC="005e" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="08" b="0037" bC="0037" sb="0026" sbC="0026" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="09" b="0038" bC="0038" sb="002a" sbC="002a" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="0a" b="0039" bC="0039" sb="0029" sbC="0029" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="0b" b="0030" bC="0030" sb="0028" sbC="0028" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="0c" b="002d" bC="002d" sb="005f" sbC="005f" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="0d" b="003d" bC="003d" sb="002b" sbC="002b" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="10" b="624b" bC="624b" sb="0071" sbC="0051" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="11" b="7530" bC="7530" sb="0077" sbC="0057" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="12" b="6c34" bC="6c34" sb="0065" sbC="0045" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="13" b="53e3" bC="53e3" sb="0072" sbC="0052" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="14" b="5eff" bC="5eff" sb="0074" sbC="0054" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="15" b="535c" bC="535c" sb="0079" sbC="0059" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="16" b="5c71" bC="5c71" sb="0075" sbC="0055" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="17" b="6208" bC="6208" sb="0069" sbC="0049" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="18" b="4eba" bC="4eba" sb="006f" sbC="004f" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="19" b="5fc3" bC="5fc3" sb="0070" sbC="0050" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="1a" b="005b" bC="005b" sb="007b" sbC="007b" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="1b" b="005d" bC="005d" sb="007d" sbC="007d" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="2b" b="005c" bC="005c" sb="007c" sbC="007c" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="1e" b="65e5" bC="65e5" sb="0061" sbC="0041" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="1f" b="5c38" bC="5c38" sb="0073" sbC="0053" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="20" b="6728" bC="6728" sb="0064" sbC="0044" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="21" b="706b" bC="706b" sb="0066" sbC="0046" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="22" b="571f" bC="571f" sb="0067" sbC="0047" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="23" b="7af9" bC="7af9" sb="0068" sbC="0048" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="24" b="5341" bC="5341" sb="006a" sbC="004a" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="25" b="5927" bC="5927" sb="006b" sbC="004b" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="26" b="4e2d" bC="4e2d" sb="006c" sbC="004c" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="27" b="003b" bC="003b" sb="003a" sbC="003a" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="28" b="0027" bC="0027" sb="0022" sbC="0022" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="2c" b="ff3a" bC="ff3a" sb="007a" sbC="005a" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="2d" b="96e3" bC="96e3" sb="0078" sbC="0058" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="2e" b="91d1" bC="91d1" sb="0063" sbC="0043" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="2f" b="5973" bC="5973" sb="0076" sbC="0056" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="30" b="6708" bC="6708" sb="0062" sbC="0042" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="31" b="5f13" bC="5f13" sb="006e" sbC="004e" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="32" b="4e00" bC="4e00" sb="006d" sbC="004d" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="33" b="002c" bC="002c" sb="003c" sbC="003c" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="34" b="002e" bC="002e" sb="003e" sbC="003e" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
    <key scancode="35" b="002f" bC="002f" sb="003f" sbC="003f" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
  </keyboard>
  <keyboard klid="0002FFFF" kname="Chinese Bopomofo">
    <key scancode="39" b="0020" bC="0020" sb="0020" sbC="0020" l="0000" lC="0000" sl="0000" slC="0000" g="0000" gC="0000" sg="0000" sgC="0000" r="0000" rC="0000" sr="0000" srC="0000" />
